In [22]:
import os
os.environ["POLARS_MAX_THREADS"] = "1"

In [23]:
import polars as pl
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

raw_df = pl.scan_csv("../data/Airline_Delay_Cause.csv")
raw_df.head().collect()

shape: (5, 21)
┌──────┬───────┬─────────┬──────────────┬───┬──────────────┬───────────┬─────────────┬─────────────┐
│ year ┆ month ┆ carrier ┆ carrier_name ┆ … ┆ weather_dela ┆ nas_delay ┆ security_de ┆ late_aircra │
│ ---  ┆ ---   ┆ ---     ┆ ---          ┆   ┆ y            ┆ ---       ┆ lay         ┆ ft_delay    │
│ i64  ┆ i64   ┆ str     ┆ str          ┆   ┆ ---          ┆ i64       ┆ ---         ┆ ---         │
│      ┆       ┆         ┆              ┆   ┆ i64          ┆           ┆ i64         ┆ i64         │
╞══════╪═══════╪═════════╪══════════════╪═══╪══════════════╪═══════════╪═════════════╪═════════════╡
│ 2022 ┆ 5     ┆ 9E      ┆ Endeavor Air ┆ … ┆ 0            ┆ 4         ┆ 0           ┆ 29          │
│      ┆       ┆         ┆ Inc.         ┆   ┆              ┆           ┆             ┆             │
│ 2022 ┆ 5     ┆ 9E      ┆ Endeavor Air ┆ … ┆ 0            ┆ 81        ┆ 0           ┆ 452         │
│      ┆       ┆         ┆ Inc.         ┆   ┆              ┆           ┆             ┆             │
│ 2022 ┆ 5     ┆ 9E      ┆ Endeavor Air ┆ … ┆ 0            ┆ 106       ┆ 0           ┆ 28          │
│      ┆       ┆         ┆ Inc.         ┆   ┆              ┆           ┆             ┆             │
│ 2022 ┆ 5     ┆ 9E      ┆ Endeavor Air ┆ … ┆ 35           ┆ 125       ┆ 0           ┆ 202         │
│      ┆       ┆         ┆ Inc.         ┆   ┆              ┆           ┆             ┆             │
│ 2022 ┆ 5     ┆ 9E      ┆ Endeavor Air ┆ … ┆ 0            ┆ 87        ┆ 0           ┆ 59          │
│      ┆       ┆         ┆ Inc.         ┆   ┆              ┆           ┆             ┆             │
└──────┴───────┴─────────┴──────────────┴───┴──────────────┴───────────┴─────────────┴─────────────┘

In [24]:
raw_df.describe()

shape: (9, 22)
┌────────────┬────────────┬──────────┬─────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ year       ┆ month    ┆ carrier ┆ … ┆ weather_d ┆ nas_delay ┆ security_ ┆ late_airc │
│ ---        ┆ ---        ┆ ---      ┆ ---     ┆   ┆ elay      ┆ ---       ┆ delay     ┆ raft_dela │
│ str        ┆ f64        ┆ f64      ┆ str     ┆   ┆ ---       ┆ f64       ┆ ---       ┆ y         │
│            ┆            ┆          ┆         ┆   ┆ f64       ┆           ┆ f64       ┆ ---       │
│            ┆            ┆          ┆         ┆   ┆           ┆           ┆           ┆ f64       │
╞════════════╪════════════╪══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 318017.0   ┆ 318017.0 ┆ 318013  ┆ … ┆ 317529.0  ┆ 317529.0  ┆ 317527.0  ┆ 317529.0  │
│ null_count ┆ 0.0        ┆ 0.0      ┆ 4       ┆ … ┆ 488.0     ┆ 488.0     ┆ 490.0     ┆ 488.0     │
│ mean       ┆ 2012.45095 ┆ 6.497844 ┆ null    ┆ … ┆ 220.56754 ┆ 1099.5164 ┆ 7.214845  ┆ 1596.0629 │
│            ┆ 7          ┆          ┆         ┆   ┆ 2         ┆ 22        ┆           ┆ 93        │
│ std        ┆ 5.678296   ┆ 3.459423 ┆ null    ┆ … ┆ 861.52144 ┆ 4636.4759 ┆ 38.854685 ┆ 4924.9506 │
│            ┆            ┆          ┆         ┆   ┆           ┆ 08        ┆           ┆ 87        │
│ min        ┆ 2003.0     ┆ 1.0      ┆ 9E      ┆ … ┆ 0.0       ┆ -19.0     ┆ 0.0       ┆ 0.0       │
│ 25%        ┆ 2007.0     ┆ 3.0      ┆ null    ┆ … ┆ 0.0       ┆ 56.0      ┆ 0.0       ┆ 79.0      │
│ 50%        ┆ 2012.0     ┆ 6.0      ┆ null    ┆ … ┆ 25.0      ┆ 203.0     ┆ 0.0       ┆ 351.0     │
│ 75%        ┆ 2018.0     ┆ 10.0     ┆ null    ┆ … ┆ 159.0     ┆ 602.0     ┆ 0.0       ┆ 1110.0    │
│ max        ┆ 2022.0     ┆ 12.0     ┆ YX      ┆ … ┆ 57707.0   ┆ 238440.0  ┆ 3760.0    ┆ 148181.0  │
└────────────┴────────────┴──────────┴─────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [25]:
print(f"Số dòng : {raw_df.collect().height}")

Số dòng : 318017

In [26]:
raw_df.collect_schema().names()

['year',
 'month',
 'carrier',
 'carrier_name',
 'airport',
 'airport_name',
 'arr_flights',
 'arr_del15',
 'carrier_ct',
 'weather_ct',
 'nas_ct',
 'security_ct',
 'late_aircraft_ct',
 'arr_cancelled',
 'arr_diverted',
 'arr_delay',
 'carrier_delay',
 'weather_delay',
 'nas_delay',
 'security_delay',
 'late_aircraft_delay']

# Tìm thời gian

In [27]:
df = raw_df.with_columns(
    pl.date("year", "month", 1).alias("flight_date") 
).drop(["year", "month"])

print(df.select(
    [
        pl.col("flight_date").min().alias("min"),
        pl.col("flight_date").max().alias("max")
    ]
).collect())

shape: (1, 2)
┌────────────┬────────────┐
│ min        ┆ max        │
│ ---        ┆ ---        │
│ date       ┆ date       │
╞════════════╪════════════╡
│ 2003-06-01 ┆ 2022-05-01 │
└────────────┴────────────┘

# Xử lý dữ liệu văn bản

## 1. Carrier

In [28]:
df.select(["carrier", "carrier_name"]).unique().filter(
    (pl.col("carrier").is_null()) | 
    (pl.col("carrier_name").is_null()) 
).collect()

shape: (1, 2)
┌─────────┬──────────────┐
│ carrier ┆ carrier_name │
│ ---     ┆ ---          │
│ str     ┆ str          │
╞═════════╪══════════════╡
│ null    ┆ null         │
└─────────┴──────────────┘

In [29]:
CARRIER_TABLE = df.select(["carrier", "carrier_name"]).unique().drop_nulls()
CARRIER_TABLE.collect()

shape: (35, 2)
┌─────────┬──────────────────────────────┐
│ carrier ┆ carrier_name                 │
│ ---     ┆ ---                          │
│ str     ┆ str                          │
╞═════════╪══════════════════════════════╡
│ DH      ┆ Atlantic Coast Airlines      │
│ HP      ┆ America West Airlines Inc.   │
│ UA      ┆ United Air Lines Inc.        │
│ MQ      ┆ Envoy Air                    │
│ NK      ┆ Spirit Air Lines             │
│ …       ┆ …                            │
│ MQ      ┆ American Eagle Airlines Inc. │
│ G4      ┆ Allegiant Air                │
│ XE      ┆ ExpressJet Airlines Inc.     │
│ QX      ┆ Horizon Air                  │
│ YX      ┆ Republic Airline             │
└─────────┴──────────────────────────────┘

### Kết luận: Chỉ cần sử dụng bảng CARRIER_TABLE, các giá trị null ở 2 cột carrier và carrier_table bị lược bỏ

In [30]:
df = df.drop_nulls(["carrier", "carrier_name"])

In [31]:
CARRIER_TABLE.collect().write_parquet("../output/carrier.parquet")

## 2. Airport

In [32]:
temp = df.select(["airport", "airport_name"]).unique().filter(
    (pl.col("airport").is_null()) | 
    (pl.col("airport_name").is_null()) 
)

In [33]:
AIRPORT_TABLE = df.select(["airport", "airport_name"]).unique().filter(
    (pl.col("airport").is_not_null()) & 
    (pl.col("airport_name").is_not_null()) 
)

AIRPORT_TABLE.collect()

shape: (420, 2)
┌─────────┬─────────────────────────────────┐
│ airport ┆ airport_name                    │
│ ---     ┆ ---                             │
│ str     ┆ str                             │
╞═════════╪═════════════════════════════════╡
│ JST     ┆ Johnstown, PA: John Murtha Joh… │
│ ECP     ┆ Panama City, FL: Northwest Flo… │
│ PGV     ┆ Greenville, NC: Pitt Greenvill… │
│ LEX     ┆ Lexington, KY: Blue Grass       │
│ BIH     ┆ Bishop, CA: Bishop Airport      │
│ …       ┆ …                               │
│ SGF     ┆ Springfield, MO: Springfield-B… │
│ ISP     ┆ Islip, NY: Long Island MacArth… │
│ LBF     ┆ North Platte, NE: North Platte… │
│ DAB     ┆ Daytona Beach, FL: Daytona Bea… │
│ CHO     ┆ Charlottesville, VA: Charlotte… │
└─────────┴─────────────────────────────────┘

In [34]:
rescue_check = AIRPORT_TABLE.join(
    temp, 
    on="airport_name", 
    how="semi"
).collect()

print(rescue_check)

shape: (3, 2)
┌─────────┬─────────────────────────────────┐
│ airport ┆ airport_name                    │
│ ---     ┆ ---                             │
│ str     ┆ str                             │
╞═════════╪═════════════════════════════════╡
│ PHX     ┆ Phoenix, AZ: Phoenix Sky Harbo… │
│ PSG     ┆ Petersburg, AK: Petersburg Jam… │
│ PIT     ┆ Pittsburgh, PA: Pittsburgh Int… │
└─────────┴─────────────────────────────────┘

### Kết luận: Chỉ cần fill các giá trị trống bằng bảng AIRPORT_TABLE

In [35]:
df = (
    df.join(
        AIRPORT_TABLE, 
        on="airport_name", 
        how="left", 
        suffix="_fixed" # Tạo cột tạm airport_fixed để đối chiếu
    )
    .with_columns([
        # Nếu cột 'airport' null thì lấy từ 'airport_fixed', không thì giữ nguyên
        pl.col("airport").fill_null(pl.col("airport_fixed"))
    ])
    .drop("airport_fixed") # Xóa cột tạm sau khi đã dùng xong
)

In [36]:
df.head().collect()

shape: (5, 20)
┌─────────┬────────────┬─────────┬────────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ carrier ┆ carrier_na ┆ airport ┆ airport_na ┆ … ┆ nas_delay ┆ security_d ┆ late_airc ┆ flight_da │
│ ---     ┆ me         ┆ ---     ┆ me         ┆   ┆ ---       ┆ elay       ┆ raft_dela ┆ te        │
│ str     ┆ ---        ┆ str     ┆ ---        ┆   ┆ i64       ┆ ---        ┆ y         ┆ ---       │
│         ┆ str        ┆         ┆ str        ┆   ┆           ┆ i64        ┆ ---       ┆ date      │
│         ┆            ┆         ┆            ┆   ┆           ┆            ┆ i64       ┆           │
╞═════════╪════════════╪═════════╪════════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 9E      ┆ Endeavor   ┆ ABE     ┆ Allentown/ ┆ … ┆ 4         ┆ 0          ┆ 29        ┆ 2022-05-0 │
│         ┆ Air Inc.   ┆         ┆ Bethlehem/ ┆   ┆           ┆            ┆           ┆ 1         │
│         ┆            ┆         ┆ Easton,    ┆   ┆           ┆            ┆           ┆           │
│         ┆            ┆         ┆ PA…        ┆   ┆           ┆            ┆           ┆           │
│ 9E      ┆ Endeavor   ┆ ABY     ┆ Albany,    ┆ … ┆ 81        ┆ 0          ┆ 452       ┆ 2022-05-0 │
│         ┆ Air Inc.   ┆         ┆ GA:        ┆   ┆           ┆            ┆           ┆ 1         │
│         ┆            ┆         ┆ Southwest  ┆   ┆           ┆            ┆           ┆           │
│         ┆            ┆         ┆ Georgia …  ┆   ┆           ┆            ┆           ┆           │
│ 9E      ┆ Endeavor   ┆ ACK     ┆ Nantucket, ┆ … ┆ 106       ┆ 0          ┆ 28        ┆ 2022-05-0 │
│         ┆ Air Inc.   ┆         ┆ MA:        ┆   ┆           ┆            ┆           ┆ 1         │
│         ┆            ┆         ┆ Nantucket  ┆   ┆           ┆            ┆           ┆           │
│         ┆            ┆         ┆ Memor…     ┆   ┆           ┆            ┆           ┆           │
│ 9E      ┆ Endeavor   ┆ AEX     ┆ Alexandria ┆ … ┆ 125       ┆ 0          ┆ 202       ┆ 2022-05-0 │
│         ┆ Air Inc.   ┆         ┆ , LA:      ┆   ┆           ┆            ┆           ┆ 1         │
│         ┆            ┆         ┆ Alexandria ┆   ┆           ┆            ┆           ┆           │
│         ┆            ┆         ┆ Int…       ┆   ┆           ┆            ┆           ┆           │
│ 9E      ┆ Endeavor   ┆ AGS     ┆ Augusta,   ┆ … ┆ 87        ┆ 0          ┆ 59        ┆ 2022-05-0 │
│         ┆ Air Inc.   ┆         ┆ GA:        ┆   ┆           ┆            ┆           ┆ 1         │
│         ┆            ┆         ┆ Augusta    ┆   ┆           ┆            ┆           ┆           │
│         ┆            ┆         ┆ Regional … ┆   ┆           ┆            ┆           ┆           │
└─────────┴────────────┴─────────┴────────────┴───┴───────────┴────────────┴───────────┴───────────┘

In [37]:
AIRPORT_TABLE.collect().write_parquet("../output/airport.parquet")

## 3. Loại bỏ cột "_name" cho dễ đọc

In [38]:
df = df.drop(["carrier_name", "airport_name"])
df.head().collect()

shape: (5, 18)
┌─────────┬─────────┬────────────┬───────────┬───┬───────────┬────────────┬────────────┬───────────┐
│ carrier ┆ airport ┆ arr_flight ┆ arr_del15 ┆ … ┆ nas_delay ┆ security_d ┆ late_aircr ┆ flight_da │
│ ---     ┆ ---     ┆ s          ┆ ---       ┆   ┆ ---       ┆ elay       ┆ aft_delay  ┆ te        │
│ str     ┆ str     ┆ ---        ┆ i64       ┆   ┆ i64       ┆ ---        ┆ ---        ┆ ---       │
│         ┆         ┆ i64        ┆           ┆   ┆           ┆ i64        ┆ i64        ┆ date      │
╞═════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪════════════╪════════════╪═══════════╡
│ 9E      ┆ ABE     ┆ 136        ┆ 7         ┆ … ┆ 4         ┆ 0          ┆ 29         ┆ 2022-05-0 │
│         ┆         ┆            ┆           ┆   ┆           ┆            ┆            ┆ 1         │
│ 9E      ┆ ABY     ┆ 91         ┆ 16        ┆ … ┆ 81        ┆ 0          ┆ 452        ┆ 2022-05-0 │
│         ┆         ┆            ┆           ┆   ┆           ┆            ┆            ┆ 1         │
│ 9E      ┆ ACK     ┆ 19         ┆ 2         ┆ … ┆ 106       ┆ 0          ┆ 28         ┆ 2022-05-0 │
│         ┆         ┆            ┆           ┆   ┆           ┆            ┆            ┆ 1         │
│ 9E      ┆ AEX     ┆ 88         ┆ 14        ┆ … ┆ 125       ┆ 0          ┆ 202        ┆ 2022-05-0 │
│         ┆         ┆            ┆           ┆   ┆           ┆            ┆            ┆ 1         │
│ 9E      ┆ AGS     ┆ 181        ┆ 19        ┆ … ┆ 87        ┆ 0          ┆ 59         ┆ 2022-05-0 │
│         ┆         ┆            ┆           ┆   ┆           ┆            ┆            ┆ 1         │
└─────────┴─────────┴────────────┴───────────┴───┴───────────┴────────────┴────────────┴───────────┘

In [39]:
df.drop_nulls().collect().write_parquet("../output/main_df.parquet")

In [40]:
with open("../output/numeric_columns.txt", "w") as f:
    # Dùng collect_schema().names() để lấy tên cột từ LazyFrame mà không bị warning
    list_col = df.collect_schema().names()
    
    # Lọc các cột cần thiết
    numeric_cols = [col for col in list_col if col not in ["carrier", "airport", "year", "month"]]
    
    f.write(",".join(numeric_cols))

In [41]:
df.select(["carrier", "airport"]).unique().collect().write_parquet("../output/carrier_airport_map.parquet")

# Với dữ liệu số 

1. Nhóm Tổng quan (Chỉ số chính)

- arr_flights: Tổng số chuyến bay dự kiến hạ cánh xuống sân bay đó.
- arr_del15: Tổng số chuyến bay bị trễ (định nghĩa trễ là trên 15 phút).
- arr_cancelled: Số chuyến bay bị hủy.
- arr_diverted: Số chuyến bay phải hạ cánh xuống sân bay khác (chuyển hướng).

2. Nhóm Tần suất trễ (_ct = Count) --> **Có bao nhiêu chuyến bị trễ bởi lý do X?**

- carrier_ct: Trễ do hãng hàng không (bảo trì, phi hành đoàn đến muộn...).
- weather_ct: Trễ do thời tiết xấu.
- nas_ct: Trễ do Hệ thống Hàng không Quốc gia (kiểm soát không lưu, sân bay quá tải...).
- security_ct: Trễ do an ninh (sơ tán nhà ga, kiểm tra an ninh...).
- late_aircraft_ct: Trễ do "hiệu ứng dây chuyền" (máy bay đến muộn từ chuyến trước nên chuyến sau bị chậm).

3. Nhóm Thời gian trễ (_delay = Minutes) --> **Nếu có trễ thì trễ bao lâu?**

- arr_delay: Tổng số phút trễ của tất cả các chuyến bay cộng lại.
- carrier_delay: Số phút trễ do lỗi của hãng.
- weather_delay: Số phút trễ do thời tiết.
- nas_delay: Số phút trễ do hệ thống NAS.
- security_delay: Số phút trễ do an ninh.
- late_aircraft_delay: Số phút trễ tích lũy do máy bay trước đến muộn.